NEP deprecate 3.8; remove parallel arguments
catalystneuro/tqdm_publisher pull request #24
Opened 2024-01-29 19:20 UTC by CodyCBakerPhD

Something's up with coverage report: https://app.codecov.io/github/catalystneuro/tqdm_publisher

Only calculating coverage of the 'tests' folder...

Also apparently company will be following NEP not python deprecation cycles so dropping 3.8 here; also removing some unneeded arguments to `pytest` in an effort to debug this

2024-01-29 19:30 UTC, CodyCBakerPhD commented
@garrettmflynn Could you do me a favor and run the pytest with coverage flag locally and see what the resulting XML file looks like? (it should have hit counters for various lines in source)

2024-01-29 19:46 UTC, garrettmflynn commented
```
<?xml version="1.0" ?>
<coverage version="7.4.0" timestamp="1706557588055" lines-valid="69" lines-covered="67" line-rate="0.971" branches-covered="0" branches-valid="0" branch-rate="0" complexity="0">
	<!-- Generated by coverage.py: https://coverage.readthedocs.io/en/7.4.0 -->
	<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/coverage-04.dtd -->
	<sources>
		<source>/Users/garrettflynn/Documents/GitHub/progress-bars</source>
	</sources>
	<packages>
		<package name="src.tqdm_publisher" line-rate="0.9706" branch-rate="0" complexity="0">
			<classes>
				<class name="__init__.py" filename="src/tqdm_publisher/__init__.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
					</lines>
				</class>
				<class name="publisher.py" filename="src/tqdm_publisher/publisher.py" complexity="0" line-rate="0.9524" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
						<line number="2" hits="1"/>
						<line number="4" hits="1"/>
						<line number="7" hits="1"/>
						<line number="8" hits="1"/>
						<line number="9" hits="1"/>
						<line number="10" hits="1"/>
						<line number="13" hits="1"/>
						<line number="14" hits="1"/>
						<line number="16" hits="1"/>
						<line number="17" hits="1"/>
						<line number="19" hits="1"/>
						<line number="21" hits="1"/>
						<line number="53" hits="1"/>
						<line number="54" hits="1"/>
						<line number="55" hits="1"/>
						<line number="57" hits="1"/>
						<line number="92" hits="1"/>
						<line number="93" hits="0"/>
						<line number="95" hits="1"/>
						<line number="96" hits="1"/>
					</lines>
				</class>
				<class name="testing.py" filename="src/tqdm_publisher/testing.py" complexity="0" line-rate="1" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
						<line number="2" hits="1"/>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
						<line number="9" hits="1"/>
						<line number="10" hits="1"/>
						<line number="11" hits="1"/>
						<line number="12" hits="1"/>
						<line number="14" hits="1"/>
						<line number="15" hits="1"/>
						<line number="16" hits="1"/>
						<line number="18" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
		<package name="tests" line-rate="0.9714" branch-rate="0" complexity="0">
			<classes>
				<class name="test_basic.py" filename="tests/test_basic.py" complexity="0" line-rate="0.9714" branch-rate="0">
					<methods/>
					<lines>
						<line number="1" hits="1"/>
						<line number="3" hits="1"/>
						<line number="5" hits="1"/>
						<line number="6" hits="1"/>
						<line number="9" hits="1"/>
						<line number="10" hits="1"/>
						<line number="11" hits="1"/>
						<line number="15" hits="1"/>
						<line number="16" hits="1"/>
						<line number="17" hits="1"/>
						<line number="19" hits="1"/>
						<line number="22" hits="1"/>
						<line number="23" hits="1"/>
						<line number="25" hits="1"/>
						<line number="27" hits="1"/>
						<line number="29" hits="1"/>
						<line number="30" hits="1"/>
						<line number="32" hits="1"/>
						<line number="33" hits="1"/>
						<line number="34" hits="1"/>
						<line number="37" hits="1"/>
						<line number="40" hits="1"/>
						<line number="41" hits="1"/>
						<line number="43" hits="1"/>
						<line number="45" hits="1"/>
						<line number="46" hits="1"/>
						<line number="49" hits="1"/>
						<line number="50" hits="1"/>
						<line number="51" hits="0"/>
						<line number="53" hits="1"/>
						<line number="54" hits="1"/>
						<line number="55" hits="1"/>
						<line number="56" hits="1"/>
						<line number="57" hits="1"/>
						<line number="58" hits="1"/>
					</lines>
				</class>
			</classes>
		</package>
	</packages>
</coverage>

```

2024-01-29 19:48 UTC, CodyCBakerPhD commented
Weird it's not ignoring `tests/test_basic.py`, can you mess with the codecov.yml or other method until it's properly ignoring that?

2024-01-29 20:00 UTC, garrettmflynn commented
Easiest way is to scope the coverage report to`src`: `pytest --cov-report xml:./codecov.xml`.

Running `pytest-cov` doesn't factor in the `codecov.yml` file.

2024-01-29 20:02 UTC, garrettmflynn commented
That Codecov wouldn't even consider `src`, though, is very weird

2024-01-29 20:10 UTC, garrettmflynn commented
How should I trigger an upload to Codecov to test these changes?

2024-01-29 20:14 UTC, CodyCBakerPhD commented
Ohhh I see

We usually do `--cov=/.` and then rely on the yaml to sort out what to ignore and such https://github.com/catalystneuro/neuroconv/blob/main/.github/workflows/testing.yml#L132

2024-01-29 20:15 UTC, CodyCBakerPhD commented
> How should I trigger an upload to Codecov to test these changes?

I've added it to this PR - once this is merged I can trigger it on `main` through the actions

2024-01-29 20:49 UTC, garrettmflynn requested changes
Got it. Looks good to me!

2024-01-29 20:57 UTC, CodyCBakerPhD commented
> Got it. Looks good to me!

Hah, your default  GitHub PR review interface was set to 'changes requested' from the other GUIDE PR 😆

2024-01-29 21:52 UTC, garrettmflynn approved these changes
Whoops! Alright, let's do it for real this time.

2024-01-29 21:52 UTC, merged

2024-01-30 00:01 UTC, CodyCBakerPhD commented
OK so long story short; the CI was 'passing' since it was first added, but was actually failing the entire time. There was a specific flag I had to set to make it fail in the CI if the upload failed

Otherwise, it does not play well with the global upload token; it rather seems to be keyed specifically to an individual repo